# Generated by Django 3.0.2 on 2020-01-26 23:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200126_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('u_student', 'University Student'), ('s_student', 'Scool(College) student'), ('u_professor', 'University Professor'), ('teacher', 'Language teacher'), ('other', 'other')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
