# Generated by Django 3.0.2 on 2020-02-09 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200126_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('u_student', 'University Student'), ('s_student', 'Scool(College) student'), ('u_professor', 'University Professor'), ('teacher', 'Language teacher'), ('other', 'Other')], max_length=30),
        ),
    ]
