# Generated by Django 3.0.2 on 2020-02-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200209_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('s_student', 'Student'), ('u_student', 'Student (university level)'), ('teacher', 'Language teacher'), ('u_professor', 'Researcher (linguistics)'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
        ),
    ]
