# Generated by Django 3.0.2 on 2020-02-22 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200209_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_connection',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='sci_mode_requests',
            field=models.IntegerField(default=100),
        ),
    ]
