# Generated by Django 3.0.2 on 2020-02-27 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200222_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_connection', models.DateField(default=datetime.date.today)),
                ('n_requests', models.IntegerField(default=100)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sci_mode_requests',
            new_name='n_requests',
        ),
    ]
