# Generated by Django 3.0.2 on 2020-02-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200227_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='last_query',
            field=models.CharField(default='', max_length=100),
        ),
    ]
