# Generated by Django 3.0.2 on 2020-02-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ip_last_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_query',
            field=models.CharField(default='', max_length=100),
        ),
    ]
