# Generated by Django 3.0.2 on 2020-02-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_last_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
