# Generated by Django 3.0.2 on 2020-03-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ip_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='last_connection',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='n_requests',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_connection',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
