# Generated by Django 3.0.2 on 2020-03-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200303_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_connection',
        ),
    ]
