# Generated by Django 3.0.2 on 2020-03-03 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_last_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_connection',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 3, 22, 33, 16, 433141, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
