# Generated by Django 3.0.2 on 2020-01-31 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordsinmovies_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='history_records',
            new_name='HistoryRecords',
        ),
    ]
